// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerLedger.Data;

#nullable disable

namespace PokerLedger.Data.Migrations
{
    [DbContext(typeof(GameDBContext))]
    [Migration("20230808071530_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("PokerLedger.Data.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameInfo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = 1,
                            GameInfo = "Person 0 played in this one",
                            GameTitle = "Poker Game 0"
                        },
                        new
                        {
                            GameID = 2,
                            GameInfo = "Person 1 played in this one",
                            GameTitle = "Poker Game 1"
                        },
                        new
                        {
                            GameID = 3,
                            GameInfo = "Person 2 played in this one",
                            GameTitle = "Poker Game 2"
                        },
                        new
                        {
                            GameID = 4,
                            GameInfo = "Person 3 played in this one",
                            GameTitle = "Poker Game 3"
                        },
                        new
                        {
                            GameID = 5,
                            GameInfo = "Person 4 played in this one",
                            GameTitle = "Poker Game 4"
                        },
                        new
                        {
                            GameID = 6,
                            GameInfo = "Person 5 played in this one",
                            GameTitle = "Poker Game 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
